use strict;
use warnings;
use Test::More;
use Mayoi::Model::Constant::Error qw/:all/;
use HTTP::Status qw/:constants/;

is BAD_REQUEST, HTTP_BAD_REQUEST, 'BAD_REQUEST';
is UNAUTHORIZED, HTTP_UNAUTHORIZED, 'UNAUTHORIZED';
is FORBIDDEN, HTTP_FORBIDDEN, 'FORBIDDEN';
is NOT_FOUND, HTTP_NOT_FOUND, 'NOT_FOUND';
is METHOD_NOT_ALLOWED, HTTP_METHOD_NOT_ALLOWED, 'METHOD_NOT_ALLOWED';
is INTERNAL_SERVER_ERROR, HTTP_INTERNAL_SERVER_ERROR, 'INTERNAL_SERVER_ERROR';
is SERVICE_UNAVAILABLE, HTTP_SERVICE_UNAVAILABLE, 'SERVICE_UNAVAILABLE';

done_testing;
